server.port: 9901

spring:
  application:
    name: book-service
eureka:
  client:
    service-url.defaultZone: http://localhost:9001/eureka/
    service-url.registryFetchIntervalSeconds: 1
  instance:
    lease-renewal-interval-in-seconds: 1

